### PR TITLE
Properly implement conditional elements.

### PR DESCRIPTION
**Pull request by rmboggs**
This should fix issues #110 and #108. Quite a bit of work went into this so please review with care.  I have also added about 8 tests related to this in the Element/Echo/Property test cases to make sure the scenarios in question are covered.  Please let me know if additional fixes are needed.

### CODE REVIEW

**Comment by rmboggs** [comment]
Successfully tested on Wim7 net-2.0 & net-4.0; Mac OS X mono-2.0 & mono-4.0.

**Comment by skolima** [comment]
Slightly messy because there's a build change bundled together with the code fix - could you unpick those?

Other than that, it looks good. Kudos for fixing something I said I would (and never got to work on it).

**Comment by rmboggs** [comment]
oh, yeah...

Let me see what I can pull out.  If I remember right, some of these build changes were to address unexpected fallout with this change.  Specifically with the vsnet and visualcpp assemblies.

Thanks for taking the time. :)

**Comment by rmboggs** [comment]
@skolima That should take care of the mess. :)

**Comment by rmboggs** [comment]
Is this ok to pull in now?

**Comment by skolima** [comment]
Much clearer now, cheers!

**Comment by rmboggs** [comment]
I'll merge this within the next 24 hours unless someone objects.

**Comment by rmboggs** [comment]
No one objected. It's going in. :)

**Pull request merged**
