### PR TITLE
Various performance improvements to reduce memory usage, and overall performance during executions of long running tasks

### PR DESCRIPTION
**Pull request by imakowski**
Performance improvements in various locations

### CODE REVIEW

**Comment by imakowski** [comment]
Could you please merge it into the master version? All changes performed to not destroy current functionality.

**Comment by imakowski** [comment]
When 0.93 version will be available?

**Comment by imakowski** [comment]
Any plans for the release?

**Comment by rmboggs** [comment]
Hi,

I'm not sure how much performance improvements this offers but there are things in here that add value.  What kinds of tests did you put these changes through?

Release plans are still up in the air, there is a milestone for 0.93 alpha release with all of the issues/pull requests that I want included in 0.93 alpha release but I don't have an estimated release date yet.

**Comment by imakowski** [comment]
Tests was done on real applications scripts. In most of cases nant creates too much strings during execution. Fixes are automatic so can me merged automatic into the master :+1:

**Comment by rmboggs** [comment]
Ok, That make sense.

It's passing the Travis CI run.  Lemme see how it runs with NAnt's test cases on Windows.  If all goes well, I'll see about pulling it into master.

**Comment by rmboggs** [comment]
Seems to work well on Windows with .NET 2.0 & 4.0.  I'm trying it on Mono on Windows now.  If that goes well, I'll pull this in.

**Comment by rmboggs** [comment]
Works ok on Mono 2.0 & 4.0 on windows. Will pull in shortly.

**Comment by imakowski** [comment]
Thanks

**Pull request merged**
